# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: ServerCore
# Author: https://www.mc-market.org/members/89497/
# Description: Essentials of a Spigot server.
# Dependencies:
#   -> PLJRApi
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  tp-delay: false #-> Should we delay the teleport of player when using /tp <player> ?
  tp-others-delay: false #-> Should we delay the teleport of player when using /tp <player> <player> ?
  tphere-delay: false #-> Should we delay the teleport of player when using /tphere <player> ?
  aspawn-delay: false #-> Should we delay the teleport of player when using /aspawn <player> ?
  always-spawn-on-spawn: false #-> Should we teleport players to spawn on every connection?
  warp-gui: true #-> Should we use the GUI for warp list? (false = Warps in chat)
  default-world: "world" #-> What is the default world to use when using commands from console?
  day-time: 1000 #-> What should be the time, when using the /day command? (in ticks)
  night-time: 13000 #-> What should be the time, when using the /night command? (in ticks)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# Menus Setup #######################################################\
############### Here, you can customize the looks of in-game menus. # \
              #######################################################  \
back-menu:
  title: "§aServerCore §8> §b/back"
  background:
    type: "BLACK_STAINED_GLASS_PANE"
    name: "§0"
  last-location:
    type: "GLOWSTONE_DUST"
    name: "§eLast location"
    lore:
      - "§fClick to teleport to your last location."
  death-location:
    type: "REDSTONE"
    name: "§cDeath location"
    lore:
      - "§fClick to teleport to your death location."

warp-menu:
  title: "§aServerCore §8> §bWarps"
  background:
    type: "BLACK_STAINED_GLASS_PANE"
    name: "§0"
  warp-item:
    type: "PAPER"
    name: "§e%warp"
    lore:
      - "§fClick to be teleported to"
      - "§e%warp§f."
#|--------------------------------------------------------------------------------------------------------------------|#

